Adding SimpleCalculator solution to Samples
unoplatform/Uno.Samples pull request #194
Opened 2022-10-21 18:34 UTC by eriklimakc

First commit of SimpleCalculator using Uno.

2022-10-21 18:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/unoplatform/Uno.Samples?pullRequest=194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/unoplatform/Uno.Samples?pullRequest=194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/unoplatform/Uno.Samples?pullRequest=194) it.</sub>

2022-10-28 14:28 UTC, francoistanguay approved these changes

2022-10-28 17:34 UTC, dansiegel requested changes

2022-10-28 17:34 UTC, dansiegel commented on UI/SimpleCalculator/SimpleCalculator.UI/Views/CalculatorMarkupView.cs
> +                .Background(Microsoft.UI.Xaml.Resource.Theme<Brush>("BackgroundBrush"))
This will need to get updated. Since this needs to be fully qualified on Android this means we need to rename the API.

2022-10-28 21:35 UTC, francoistanguay approved these changes

2022-10-31 23:37 UTC, merged