chore: Removing KeyValues and assigning VirtualKeys into Calculator.
unoplatform/Uno.Samples pull request #295
Opened 2023-01-06 18:05 UTC by eriklimakc

2023-01-06 18:06 UTC, eriklimakc commented
Awaiting for a fix on Reactive Generator to proceed on this.

2023-01-09 15:32 UTC, dansiegel requested changes

2023-01-09 15:32 UTC, dansiegel commented on reference/SimpleCalculator/SimpleCalculator.Shared/Business/Calculator.cs
> +            _ => Input(KeyInput.None)
there shouldn't be a reason to call the Input with KeyInput.None.. just return `this`

2023-01-09 15:32 UTC, dansiegel commented on reference/SimpleCalculator/SimpleCalculator.Shared/Business/Calculator.cs
> +    None
there is no reason for a None value

2023-01-09 15:47 UTC, dansiegel approved these changes

2023-01-09 15:48 UTC, merged