chore: Adding the counter app to Uno.Samples
unoplatform/Uno.Samples pull request #639
Opened 2024-03-14 17:12 UTC by vatsashah45

2024-03-15 15:31 UTC, agneszitte reviewed
@vatsashah45, @eriklimakc 
Please add:
- A proper readme file with info + screenshots examples for the counter sample in the reference/Counter folder 
- Add the Counter sample in the list of samples in the global readme of the repo

2024-03-15 15:34 UTC, eriklimakc commented
> @vatsashah45, @eriklimakc Please add:
> 
> * A proper readme file with info + screenshots examples for the counter sample in the reference/Counter folder
> * Add the Counter sample in the list of samples in the global readme of the repo

@vatsashah45 we can do something similar to what was done to [ChatGPT Sample](https://github.com/unoplatform/Uno.Samples/tree/master/UI/ChatGPT).

cc @agneszitte

2024-04-05 08:59 UTC, eriklimakc requested changes

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVVM/Counter/Counter.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVVM/Counter/Counter.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVUX/global.json
> +    "Uno.Sdk": "5.2.0-dev.2103"
Update Uno.Sdk.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVUX/Directory.Build.props
> +    <DotNetVersion>net8.0</DotNetVersion>
```suggestion
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVUX/Directory.Build.props
> +  </PropertyGroup>
Update uno packages.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVUX/Counter/Counter.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVUX/Counter/Counter.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVVM/Directory.Build.props
> +    <DotNetVersion>net8.0</DotNetVersion>
```suggestion
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVVM/Directory.Build.props
> +  </PropertyGroup>
Update uno packages.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVVM/global.json
> +    "Uno.Sdk": "5.2.0-dev.2103"
Update Uno.Sdk.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVVM/Counter/Counter.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVVM/Counter/Counter.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVUX/global.json
> +    "Uno.Sdk": "5.2.0-dev.2103"
Update Uno.Sdk.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVUX/Directory.Build.props
> +    <DotNetVersion>net8.0</DotNetVersion>
```suggestion
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVUX/Directory.Build.props
> +  </PropertyGroup>
Update uno packages.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVUX/Counter/Counter.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/XAML-MVUX/Counter/Counter.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVVM/global.json
> +    "Uno.Sdk": "5.2.0-dev.2103"
Update Uno.Sdk.

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVVM/Directory.Build.props
> +    <DotNetVersion>net8.0</DotNetVersion>
```suggestion
```

2024-04-05 08:59 UTC, eriklimakc commented on reference/Counter/CSharp-MVVM/Directory.Build.props
> +  </PropertyGroup>
Update uno packages.

2024-04-17 15:40 UTC, eriklimakc reviewed
Looks great. Can we just move the solution content from, say, 'CSharp-MVUX/Counter' to 'CSharp-MVUX/'? We don't need a 'Counter' directory within the 4 versions.

2024-04-17 15:53 UTC, eriklimakc approved these changes

2024-04-18 14:21 UTC, agneszitte commented
Closing this PR as the work will be done with https://github.com/unoplatform/Uno.Samples/pull/669

2024-04-18 14:21 UTC, closed without merging