feat: SingleProject - SimpleCalc
unoplatform/Uno.Samples pull request #641
Opened 2024-03-15 19:21 UTC by vatsashah45

2024-03-18 11:18 UTC, eriklimakc commented
It would be nice if we had a readme file similar to what we have for ChatGPT: https://github.com/unoplatform/Uno.Samples/tree/master/UI/ChatGPT

 - Intro
 - Screenshot
 - Getting Started (if anything needs to be setup like the API Key in TubePlayer - https://github.com/unoplatform/Uno.Samples/pull/640)
 - Code base (since SimpleCalc and Counter app has multiple versions, no need to specify files extensions like .xaml or .cs)
 - Docs to key features like (MVUX, C# Markup, etc) 

No need for a Architecture Diagram though (IMO).

And same for Counter App - https://github.com/unoplatform/Uno.Samples/pull/639

2024-03-18 15:55 UTC, eriklimakc commented
@vatsashah45 I think we're missing the other variations of SimpleCalc. I only see CSharp + MVVM.

2024-03-27 16:33 UTC, eriklimakc commented
We need to bring back Unit tests for SimpleCalc.

2024-04-05 08:26 UTC, eriklimakc requested changes

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/CSharp-MVUX/SimpleCalculator/SimpleCalculator.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/CSharp-MVVM/SimpleCalculator/SimpleCalculator.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/XAML-MVUX/SimpleCalculator/SimpleCalculator.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/XAML-MVVM/SimpleCalculator/SimpleCalculator.csproj
> +    </TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/XAML-MVUX/SimpleCalculator/SimpleCalculator.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:26 UTC, eriklimakc commented on reference/SimpleCalc/XAML-MVVM/SimpleCalculator/SimpleCalculator.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-19 21:24 UTC, agneszitte commented
Closing this PR in favor of https://github.com/unoplatform/Uno.Samples/pull/671

2024-04-19 21:24 UTC, closed without merging