feat: SIngleProject - Commerce
unoplatform/Uno.Samples pull request #644
Opened 2024-03-22 03:02 UTC by vatsashah45

2024-03-26 18:15 UTC, eriklimakc commented
Sample updated with latest template.

Known issues so far:

1. **WinAppSDK** and **Android** The app uses the file **products.json** to store the products info. This file lives in the project root directory, but this file is not found by the code when trying to load the products. It only worked for Windows Packaged when I moved the file to Assets. But it didn't work for Android nor Windows Unpackaged.

2. When running the app on **Desktop** no windows is launched. Nothing really happens.

3. On **WASM** the app is launched, but just a black screen is shown.

I know there are more issues related to loading data. I will post them later after I test it more.

2024-04-05 08:45 UTC, eriklimakc requested changes

2024-04-05 08:45 UTC, eriklimakc commented on reference/Commerce/Commerce/Commerce.csproj
> +	</TargetFrameworks>
```suggestion
    <TargetFrameworks>
      net8.0-desktop;
      net8.0-android;
      net8.0-ios;
      net8.0-maccatalyst;
      net8.0-windows10.0.19041;
      net8.0-browserwasm;
    </TargetFrameworks>
```

2024-04-05 08:45 UTC, eriklimakc commented on reference/Commerce/Directory.Build.props
> +    <DotNetVersion>net8.0</DotNetVersion>
```suggestion
```

2024-04-17 18:10 UTC, agneszitte reviewed
@vatsashah45, @eriklimakc 
Few comments:
- Not sure if we can have a way to avoid having a Commerce folder inside an another Commerce folder here
- Remove unnecessary files
- And finally, if you can add a proper ReadMe for the sample please
![image](https://github.com/unoplatform/Uno.Samples/assets/16295702/5668f4a4-3e12-42f6-8b16-52299b76dd08)

---
To have a structure similar to what we have for ToDo here, with a `src` folder with the source inside, a proper README.md with the details of the sample, and a `doc` folder for additional documentation or assets needed for the README for example.
![image](https://github.com/unoplatform/Uno.Samples/assets/16295702/103214f6-8185-4510-af5f-87f4dd99806f)
(cc @LProulx86 as well so we can use the same structure for the others samples)

2024-04-23 18:29 UTC, eriklimakc commented
We're currently facing this issue on this app - https://github.com/unoplatform/uno/issues/16430

2024-05-10 17:17 UTC, agneszitte commented
> We're currently facing this issue on this app - [unoplatform/uno#16430](https://github.com/unoplatform/uno/issues/16430)

@eriklimakc, @vatsashah45 now that https://github.com/unoplatform/uno/issues/16430 is closed, are there any issues left to finish the migration, please?
(cc @nickrandolph)

2024-05-10 17:42 UTC, eriklimakc commented
> @eriklimakc, @vatsashah45 now that [unoplatform/uno#16430](https://github.com/unoplatform/uno/issues/16430) is closed, are there any issues left to finish the migration, please? (cc @nickrandolph)

Yes, I don't see the build error anymore, so that's fixed. But I see a regression, the Uno.Extensions.Storage.FileStorage issue (https://github.com/unoplatform/uno-private/issues/408) is back only on wasm, and that prevents products from loading:

![image](https://github.com/unoplatform/Uno.Samples/assets/114886335/95d6fb8a-fbe0-4dfe-a445-0e119d0cf24f)

cc @agneszitte @jeromelaban @nickrandolph

2024-05-29 14:35 UTC, rajamatt commented
With latest packages the warnings for everything related to `appsettings` still appear on Wasm and other platforms:
![image](https://github.com/unoplatform/Uno.Samples/assets/70542961/641ab731-07be-4d1d-ac82-f11941999919)

However, the `products.json` file does not appear in the warnings. In fact, all the products are loaded and all feeds with products are working as expected.

cc: @agneszitte

2024-05-29 14:36 UTC, rajamatt commented
## Favorites
- [ ] All items are favorited by default but they don't appear in the Favorites feed, we have to unfavorite them and favorite them again for them to appear in the Favorites feed.

2024-05-29 14:41 UTC, rajamatt commented
## ProductsPage (search page)
- [ ] The "Products found" count is hardcoded

https://github.com/unoplatform/Uno.Samples/blob/bc7377700aae3c1721283b8ed8890bffda051903/reference/Commerce/src/Commerce/Views/ProductsPage.xaml#L66

- [ ] Searching for products only works if a filter is selected first
- [ ] Clicking on an item in the Search doesn't do anything (should it?)

2024-05-29 14:43 UTC, rajamatt commented
## Miscellaneous
- [ ] About 1/5 of the time, navigating to the profile page causes a COMException (I think its because the profile pictures are random and one of them might be problematic but I'm not sure)

![image](https://github.com/unoplatform/Uno.Samples/assets/70542961/3751a1b5-8f82-4e63-9cc3-819335cbade7)

- Back buttons aren't visible but are functional (not sure if it's theming related or not)

![image](https://github.com/unoplatform/Uno.Samples/assets/70542961/75954934-8490-4c2f-a44a-1a28579b6eff)

- The left hand navbar's items could be spaced a bit better (they are very close together and the focus background stacks on adjacent items)

![image](https://github.com/unoplatform/Uno.Samples/assets/70542961/ced51585-f337-4564-829f-9c7929210aca)

2024-06-04 19:52 UTC, kazo0 commented
@rajamatt can you create separate issues for those things you've noticed. And I can also reproduce them on current master so it doesnt seem to be related to this pr

2024-06-05 00:01 UTC, agneszitte commented
Related issues: 
- https://github.com/unoplatform/Uno.Samples/issues/735

2024-06-05 13:19 UTC, rajamatt commented
> @rajamatt can you create separate issues for those things you've noticed. And I can also reproduce them on current master so it doesnt seem to be related to this pr

Done

2024-06-11 13:26 UTC, kazo0 approved these changes

2024-06-11 13:26 UTC, kazo0 approved these changes

2024-06-19 16:41 UTC, merged