feat: SingleProject - ToDo
unoplatform/Uno.Samples pull request #647
Opened 2024-03-27 17:23 UTC by vatsashah45

2024-04-05 08:34 UTC, eriklimakc requested changes

2024-04-05 08:34 UTC, eriklimakc commented on reference/ToDo/ToDo/ToDo/ToDo.csproj
> +    <SingleProject>true</SingleProject>
```suggestion
    <UnoSingleProject>true</UnoSingleProject>
```

2024-04-05 08:34 UTC, eriklimakc commented on reference/ToDo/ToDo/Directory.Build.props
> +  </PropertyGroup>
Would be nice to update those to a more up-to-date version.

2024-04-24 11:52 UTC, eriklimakc commented
## Known issues

- [ ] Resizing the app to make it narrow on **Windows** causes the app to crash
- [ ] When trying to launch on **Desktop** an exception is thrown: `Could not load file or assembly 'Uno.Extensions.Authentication.MSAL.WinUI"`.
- [ ] Data not being loaded on **Android**. "An error occured." message is displayed. Suspecting of https://github.com/unoplatform/uno/issues/16430

2024-05-10 17:20 UTC, agneszitte commented
@eriklimakc, @vatsashah45 
@dansiegel left some details for https://github.com/unoplatform/uno/issues/16439#issuecomment-2083258997
Are there any additional blockers left for migrating ToDo, please?
(cc @nickrandolph)

2024-05-17 02:50 UTC, agneszitte commented
fyi @eriklimakc I currently have some local changes with the latest versions and additional fixes.
I will finish the work tomorrow and list the leftover issues

2024-06-06 15:23 UTC, agneszitte commented
Closing this PR in favor of https://github.com/unoplatform/Uno.Samples/pull/745

2024-06-06 15:23 UTC, closed without merging